"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const Circle_1 = __importDefault(require("./shape/equilateral/Circle"));
const Square_1 = __importDefault(require("./shape/equilateral/Square"));
const Memory_1 = __importDefault(require("./user/memory/Memory"));
const Guest_1 = __importDefault(require("./user/Guest"));
const Rectangle_1 = __importDefault(require("./shape/equilateral/non/Rectangle"));
const Member_1 = __importDefault(require("./user/premium/Member"));
let s1 = new Circle_1.default();
s1.a = 5;
console.log('s1.area()', s1.area());
let s2 = new Square_1.default();
s2.a = 4;
console.log('s2.area()', s2.area());
let db = new Memory_1.default();
let u1 = new Guest_1.default(db);
u1.addShape(s1);
u1.addShape(s2);
console.log('u1.averageShapeArea', u1.averageShapeArea);
console.log('u1.shapeAreas', u1.shapeAreas);
let s3 = new Rectangle_1.default();
s3.a = 6;
s3.b = 7;
console.log('s3.area()', s3.area());
console.log('s3.circumference()', s3.circumference());
let u2 = new Member_1.default(db);
u2.addShape(s1);
u2.addShape(s2);
u2.addShape(s3);
console.log('u2.averageShapeArea', u2.averageShapeArea);
console.log('u2.shapeAreas', u2.shapeAreas);
console.log('u2.averageShapeCircumference', u2.averageShapeCircumference);
console.log('u2.shapeCircumferences', u2.shapeCircumferences);
